# TCL File Generated by Component Editor 16.1
# Fri Jul 14 17:33:37 MSK 2017
# DO NOT MODIFY


# 
# addr_shifter "addr_shifter" v1.0
#  2017.07.14.17:33:37
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module addr_shifter
# 
set_module_property DESCRIPTION ""
set_module_property NAME addr_shifter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My Group"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME addr_shifter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL addr_shifter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file addr_shifter.v VERILOG PATH addr_shifter.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point output_bus
# 
add_interface output_bus avalon start
set_interface_property output_bus addressUnits SYMBOLS
set_interface_property output_bus associatedClock clock_source
set_interface_property output_bus associatedReset reset_sink
set_interface_property output_bus bitsPerSymbol 8
set_interface_property output_bus burstOnBurstBoundariesOnly false
set_interface_property output_bus burstcountUnits WORDS
set_interface_property output_bus doStreamReads false
set_interface_property output_bus doStreamWrites false
set_interface_property output_bus holdTime 0
set_interface_property output_bus linewrapBursts false
set_interface_property output_bus maximumPendingReadTransactions 0
set_interface_property output_bus maximumPendingWriteTransactions 0
set_interface_property output_bus readLatency 0
set_interface_property output_bus readWaitTime 1
set_interface_property output_bus setupTime 0
set_interface_property output_bus timingUnits Cycles
set_interface_property output_bus writeWaitTime 0
set_interface_property output_bus ENABLED true
set_interface_property output_bus EXPORT_OF ""
set_interface_property output_bus PORT_NAME_MAP ""
set_interface_property output_bus CMSIS_SVD_VARIABLES ""
set_interface_property output_bus SVD_ADDRESS_GROUP ""

add_interface_port output_bus output_address address Output 32
add_interface_port output_bus output_waitrequest waitrequest Input 1
add_interface_port output_bus output_readdata readdata Input 32
add_interface_port output_bus output_read read Output 1


# 
# connection point input_bus
# 
add_interface input_bus avalon end
set_interface_property input_bus addressUnits SYMBOLS
set_interface_property input_bus associatedClock clock_sink
set_interface_property input_bus associatedReset reset_sink
set_interface_property input_bus bitsPerSymbol 8
set_interface_property input_bus burstOnBurstBoundariesOnly false
set_interface_property input_bus burstcountUnits WORDS
set_interface_property input_bus explicitAddressSpan 0
set_interface_property input_bus holdTime 0
set_interface_property input_bus linewrapBursts false
set_interface_property input_bus maximumPendingReadTransactions 0
set_interface_property input_bus maximumPendingWriteTransactions 0
set_interface_property input_bus readLatency 0
set_interface_property input_bus readWaitTime 1
set_interface_property input_bus setupTime 0
set_interface_property input_bus timingUnits Cycles
set_interface_property input_bus writeWaitTime 0
set_interface_property input_bus ENABLED true
set_interface_property input_bus EXPORT_OF ""
set_interface_property input_bus PORT_NAME_MAP ""
set_interface_property input_bus CMSIS_SVD_VARIABLES ""
set_interface_property input_bus SVD_ADDRESS_GROUP ""

add_interface_port input_bus input_read read Input 1
add_interface_port input_bus input_readdata readdata Output 32
add_interface_port input_bus input_address address Input 12
add_interface_port input_bus input_waitrequest waitrequest Output 1
set_interface_assignment input_bus embeddedsw.configuration.isFlash 0
set_interface_assignment input_bus embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment input_bus embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment input_bus embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink input_clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink input_reset reset Input 1


# 
# connection point clock_source
# 
add_interface clock_source clock start
set_interface_property clock_source associatedDirectClock ""
set_interface_property clock_source clockRate 0
set_interface_property clock_source clockRateKnown false
set_interface_property clock_source ENABLED true
set_interface_property clock_source EXPORT_OF ""
set_interface_property clock_source PORT_NAME_MAP ""
set_interface_property clock_source CMSIS_SVD_VARIABLES ""
set_interface_property clock_source SVD_ADDRESS_GROUP ""

add_interface_port clock_source output_clk clk Output 1

